### ISSUE TITLE
certain instruction data cause a StreamError in MangoInstructionReporter

### ISSUE THREAD

**Issue by edgarxi** [blockworks-foundation/mango-explorer#43] opened 2022-02-10 06:25 UTC
The second and third mango instructions in [this mango transaction](https://solscan.io/tx/5uZ1DpcCiEPEPdRr92xSM99xsSgWxmtH1tm8PENPMRojFED25ygrbvT2ddyTsnn37tc2fLFU4e7TbgZuAmkf3bvp) seem to cause an error in `mango.instructionreporter.MangoInstructionReporter`

minimal Python example, with instruction data taken from Instruction 1 of [this tx](4iFXttW4YvgHEQseDg3n9WPqwV1GwFqaSuhdDdNVdKthowTYy2YKvTCaFC6r5kazppzKuvBPZYYEtwhaUhRoXAtc)

```python
from base58 import b58decode
from mango.instructionreporter import MangoInstructionReporter
from solana.transaction import TransactionInstruction

MANGO_PROGRAM_ADDRESS = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"

instruction_data = "3QTfBEZUonKTiyJa4QWgbYKWvYcaAj3oxZf1TYnjs"  # appears to be a PlacePerpOrder 
raw_data = b58decode(instruction_data)

instruction = TransactionInstruction(
     keys=[], program_id=MANGO_PROGRAM_ADDRESS, data=raw_data
)

report =  MangoInstructionReporter(MANGO_PROGRAM_ADDRESS).report(instruction=instruction) # causes a StreamError

```

the above code causes the following error (truncated):

```
File ~/.pyenv/versions/3.9.10/envs/py39/lib/python3.9/site-packages/construct/core.py:91, in stream_read(stream, length, path)
     89     raise StreamError("stream.read() failed, requested %s bytes" % (length,), path=path)
     90 if len(data) != length:
---> 91     raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
     92 return data

StreamError: Error in path (parsing) -> reduce_only
stream read less than specified amount, expected 1, found 0
``` 

It seems to happen with `PlacePerpOrder`instructions that occur after a `CancelAllPerpOrders` instructions
Could the struct that parses perp orders be out of date? Or am I using the module incorrectly?

**Comment by OpinionatedGeek** [comment] 2022-02-10 11:24
Apologies for this. You're using the module correctly, this was an odd problem that wasn't handled.

The crux of the problem was that PlacePerpOrder can take an optional 'reduce only' flag now. It's optional - it doesn't need to be specified, and old orders won't have specified it - but it wasn't marked as optional in the Struct that was used to parse the data. This meant that parser failed to load order data that didn't include this parameter, even though it was optional.

Transaction 5uZ1DpcCiEPEPdRr92xSM99xsSgWxmtH1tm8PENPMRojFED25ygrbvT2ddyTsnn37tc2fLFU4e7TbgZuAmkf3bvp had such an order, which made it fail.

I took advantage of this change to fix a few more problems in the transaction display code. For example, you can now run `show-transaction --signature 5uZ1DpcCiEPEPdRr92xSM99xsSgWxmtH1tm8PENPMRojFED25ygrbvT2ddyTsnn37tc2fLFU4e7TbgZuAmkf3bvp` and you'll see:
```
« TransactionScout 2022-02-10 06:07:12: CancelAllPerpOrders, PlacePerpOrder, PlacePerpOrder
    Sender:
        None
    Succeeded:
        True
    Group:
        mainnet.1 [98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue]
    Signatures:
        5uZ1DpcCiEPEPdRr92xSM99xsSgWxmtH1tm8PENPMRojFED25ygrbvT2ddyTsnn37tc2fLFU4e7TbgZuAmkf3bvp
    Instructions:
        « Mango Instruction CancelAllPerpOrders: None
            Program ID: mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68
            Data: 2700000020
            Key[ 0]: 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
            Key[ 1]: GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
            Key[ 2]: HSH3LftAhgNEQmpNRuE1ghnbqVHsxt8edvid1zdLxH5C
            Key[ 3]: EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9
            Key[ 4]: BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9
            Key[ 5]: 8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs
        »
        « Mango Instruction PlacePerpOrder: side: BUY, order_type: POST_ONLY, price: 8964, quantity: 294117, client_order_id: 7062958746293602362, reduce_only: None
            Program ID: mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68
            Data: 0c0000000423000000000000e57c0400000000003a8811008fab04620002
            Key[ 0]: 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
            Key[ 1]: GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
            Key[ 2]: HSH3LftAhgNEQmpNRuE1ghnbqVHsxt8edvid1zdLxH5C
            Key[ 3]: EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu
            Key[ 4]: EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9
            Key[ 5]: BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9
            Key[ 6]: 8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs
            Key[ 7]: 5Grgo9kLu692SUcJ6S7jtbi1WkdwiyRWgThAfN1PcvbL
            Key[ 8]: ATnF2mEcaRwjq68dceUL4Wxyv1hkUHQbKW4damhn2BuT
            Key[ 9]: 5tenh761mc1bHujweU2RH3vDs9HzxTjyfEW1BuxHZHXb
            Key[10]: 8KBAf352HP8QBbSxgUBezGqjja7R8GtjoiGujX1XTN5w
            Key[11]: GPJPVRcGoPyqvPncBWhNXoH1WU4BtLp4aufkPRYmTEXT
            Key[12]: 11111111111111111111111111111111
            Key[13]: 11111111111111111111111111111111
            Key[14]: 11111111111111111111111111111111
            Key[15]: 11111111111111111111111111111111
            Key[16]: 11111111111111111111111111111111
            Key[17]: 11111111111111111111111111111111
            Key[18]: 11111111111111111111111111111111
            Key[19]: 11111111111111111111111111111111
            Key[20]: 11111111111111111111111111111111
            Key[21]: 11111111111111111111111111111111
            Key[22]: 11111111111111111111111111111111
            Key[23]: 11111111111111111111111111111111
        »
        « Mango Instruction PlacePerpOrder: side: SELL, order_type: POST_ONLY, price: 8986, quantity: 152512, client_order_id: 7062958746293602363, reduce_only: None
            Program ID: mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68
            Data: 0c0000001a23000000000000c0530200000000003b8811008fab04620102
            Key[ 0]: 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
            Key[ 1]: GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
            Key[ 2]: HSH3LftAhgNEQmpNRuE1ghnbqVHsxt8edvid1zdLxH5C
            Key[ 3]: EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu
            Key[ 4]: EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9
            Key[ 5]: BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9
            Key[ 6]: 8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs
            Key[ 7]: 5Grgo9kLu692SUcJ6S7jtbi1WkdwiyRWgThAfN1PcvbL
            Key[ 8]: ATnF2mEcaRwjq68dceUL4Wxyv1hkUHQbKW4damhn2BuT
            Key[ 9]: 5tenh761mc1bHujweU2RH3vDs9HzxTjyfEW1BuxHZHXb
            Key[10]: 8KBAf352HP8QBbSxgUBezGqjja7R8GtjoiGujX1XTN5w
            Key[11]: GPJPVRcGoPyqvPncBWhNXoH1WU4BtLp4aufkPRYmTEXT
            Key[12]: 11111111111111111111111111111111
            Key[13]: 11111111111111111111111111111111
            Key[14]: 11111111111111111111111111111111
            Key[15]: 11111111111111111111111111111111
            Key[16]: 11111111111111111111111111111111
            Key[17]: 11111111111111111111111111111111
            Key[18]: 11111111111111111111111111111111
            Key[19]: 11111111111111111111111111111111
            Key[20]: 11111111111111111111111111111111
            Key[21]: 11111111111111111111111111111111
            Key[22]: 11111111111111111111111111111111
            Key[23]: 11111111111111111111111111111111
        »
    Accounts:
        HSH3LftAhgNEQmpNRuE1ghnbqVHsxt8edvid1zdLxH5C
        GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
        EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9
        BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9
        8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs
        5Grgo9kLu692SUcJ6S7jtbi1WkdwiyRWgThAfN1PcvbL
        98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
        EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu
        ATnF2mEcaRwjq68dceUL4Wxyv1hkUHQbKW4damhn2BuT
        5tenh761mc1bHujweU2RH3vDs9HzxTjyfEW1BuxHZHXb
        8KBAf352HP8QBbSxgUBezGqjja7R8GtjoiGujX1XTN5w
        GPJPVRcGoPyqvPncBWhNXoH1WU4BtLp4aufkPRYmTEXT
        11111111111111111111111111111111
        mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68
    Messages:
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [1]
        Program log: Mango: CancelAllPerpOrders | limit=32
        Mango CancelAllPerpOrdersLog Container:
            mangoGroup = 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
            mangoAccount = GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
            marketIndex = 12
            allOrderIds_count = 2
            allOrderIds = ListContainer:
                165375060620806120171556
                165762442246354040887260
            canceledOrderIds_count = 2
            canceledOrderIds = ListContainer:
                165375060620806120171556
                165762442246354040887260
        Mango MngoAccrualLog Container:
            mangoGroup = 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue
            mangoAccount = GR8wiP7NfHR8nihLjiADRoRM7V7aUvtTfUnkBy8Zkd5T
            marketIndex = 12
            mngoAccrual = 0
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 25720 of 200000 compute units
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [1]
        Program log: Mango: PlacePerpOrder client_order_id=7062958746293602362
        Program log: bid on book order_id=165375060620806120171553 quantity=294117 price=8964
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 41882 of 200000 compute units
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [1]
        Program log: Mango: PlacePerpOrder client_order_id=7062958746293602363
        Program log: ask on book order_id=165762442246354040887263 quantity=152512 price=8986
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 42365 of 200000 compute units
        Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
    Tokens In:
        None
    Tokens Out:
        None
    Token Changes:
        None
»
```
Running your minimal Python example to reproduce the problem now outputs:
```
« Mango Instruction PlacePerpOrder: side: BUY, order_type: POST_ONLY, price: 8964, quantity: 294117, client_order_id: 7062958746293602362, reduce_only: None
    Program ID: mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68
    Data: 0c0000000423000000000000e57c0400000000003a8811008fab04620002
    None
»
```
This fix is now in Github ([63e3a9d](https://github.com/blockworks-foundation/mango-explorer/commit/63e3a9dd88990e8dba8c08c0b02468f663c249e4)) and will be available in the next release.

**Closed by OpinionatedGeek** 2022-02-10 11:24 UTC
